### ISSUE TITLE
Fit latent codes of a given image

### ISSUE THREAD

**Issue by Pbb-land** [mcbuehler/VariTex#3]
Hi, thanks for your nice work! I tried to fit latent codes(z,ep,sp) of a wild image, using Adam optimizer and rgb L1 loss between images,but could not get an ideal result.Could you please offer a strategy or official code to fit codes of a given image?

**Comment by 0three** [comment]
I need it for comparison, too. Thanks!

**Comment by mcbuehler** [comment]
Thank you for your interest in our work. 

For geometry, you can obtain shape and expression parameters via the [basel face pipeline](https://github.com/unibas-gravis/basel-face-pipeline) (Section __Face Reconstruction from 2D Image__).

For appearance, you can run your masked input image through the pretrained encoder (download via the link "Pretrained models" in the [README](https://github.com/mcbuehler/VariTex/blob/main/README.md)) and use the mean of the predicted Gaussian distribution as initialization for your optimization. Here is how you can use our [demo notebook](https://github.com/mcbuehler/VariTex/blob/main/demo.ipynb) to extract the latent code from a masked input image tensor `image_in`:
```
batch = demo.pipeline.generator.forward_encode({DIK.IMAGE_IN_ENCODE: image_in.unsqueeze(0).cuda()}, 0)
batch = demo.pipeline.generator.forward_encoded2latent_distribution(batch)
z = batch[DIK.STYLE_LATENT_MU]
```

Please note that the predicted `z` code might not generate the exact same identity (Fig. 13 in the supplementary material), but they should look somehow similar. We leave identity-preserving reconstruction of in-the-wild images for future work.
