### ISSUE TITLE
how to apply a custom 3d face model?

### ISSUE THREAD

**Issue by liuLannister** [mcbuehler/VariTex#4]
hello, can i apply a custom 3d face model (such as MeshTalk) instead of Basel Face Model to generating posed meshes?

**Comment by ImistroI** [comment]
that would also interest me

**Comment by mcbuehler** [comment]
Yes, it is possible to use any 3D face model, as long as it has a UV parameterization.

Codewise, you will have to update the UV rendering in `varitex/data/uv_factory.py`.
