### ISSUE TITLE
 Can I train with my own dataset?

### ISSUE THREAD

**Issue by dayu1979** [mcbuehler/VariTex#5]
good work,
Can I train with my own dataset?how to preprocess data?
thanks

**Comment by mcbuehler** [comment]
Yes, you can use your dataset. Please check out the README about the [processed FFHQ dataset](https://github.com/mcbuehler/VariTex?tab=readme-ov-file#data) to see the expected data format.

Unfortunately, we cannot release our preprocessing pipeline.
