### ISSUE TITLE
Make my own dataset

### ISSUE THREAD

**Issue by kuwan2e** [mcbuehler/VariTex#8]
Hi, thanks for your work.
Could you pls tell me how to generate these files? I do not need your pipeline, but pls tell me the method that you choose. Thanks

ep shape: (69991, 100)
sp shape: (69991, 199)
latents shape: (10000, 2, 256)
filename shape: (69991,)
R shape: (69991, 3, 3)
t shape: (69991, 3)
s shape: (69991, 1)
segmentation shape: (69991, 512, 512)
 uv.shape
(69991, 512, 512, 2)

**Comment by mcbuehler** [comment]
Hi, 

I wrote a fitting pipeline that jointly fits the Basel Face Model (shape `sp`, expression `ep`) and a similarity transform (rotation `R`, translation `t`, scale `s`). The pipeline uses facial landmarks from [Mediapipe](https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker). 
I trained a segmentation network on [CelebAMask-HQ](https://github.com/switchablenorms/CelebAMask-HQ) to obtain the segmentations.

The UVs are rasterized with pytorch3d, see the implementation [here](https://github.com/mcbuehler/VariTex/blob/a25979f96d600ed839799450958ace8952ce375a/mutil/renderer.py#L158).

The latents are predicted by our encoder after training the full pipeline. Please see `z_face` and `z_additive` in Fig. 2.

The filenames correspond to the FFHQ filenames.

Please see Sec. 2.1 in the [supplementary material](https://dataset.ait.ethz.ch/downloads/varitex/supp.pdf) for a more detailed explanation of the preprocessing pipeline.
